name: 'Terraform Security Scan'
description: 'Run tfsec security scan on Terraform code'

runs:
  using: 'composite'
  steps:
    - name: tfsec Security Scan
      uses: aquasecurity/tfsec-action@v1.0.3
      with:
        soft_fail: false 