name: 'Terraform Validate'
description: 'Run Terraform validation and quality checks'

inputs:
  terraform-version:
    description: 'Terraform version to use'
    required: false
    default: '1.6.6'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform-version }}

    - name: Terraform Format Check
      shell: bash
      run: terraform fmt -check -recursive

    - name: Terraform Validate
      shell: bash
      run: terraform validate 